# Generated by Django 4.1.7 on 2023-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('dateOfJoining', models.DateField()),
                ('photoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
